#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_ROOT="${INSTALL_ROOT:-/opt/mozaic-office}"
CONFIG_ROOT="${CONFIG_ROOT:-/etc/mozaic-office}"
RUNTIME_DIR="${INSTALL_ROOT}/runtime"
STATE_FILE="${CONFIG_ROOT}/install.env"
LOG_FILE="/var/log/mozaic-office-install.log"

FRONTEND_REPO="https://github.com/rakibulinux/voice-agent-frontend.git"
BACKEND_REPO="https://github.com/shayanfh/ai-agent-dashboard.git"
VOICE_AGENT_REPO="https://github.com/shayanfh/ai-agent-dashboard-voice-agent.git"

log() { printf '[mozaic-office] %s\n' "$*" | tee -a "$LOG_FILE"; }
die() { log "ERROR: $*"; exit 1; }
on_error() { log "Installation failed at line $1. Inspect $LOG_FILE."; }
trap 'on_error "$LINENO"' ERR

require_root() {
  [[ ${EUID} -eq 0 ]] || die "Run this installer with sudo."
}

check_os() {
  # shellcheck disable=SC1091
  source /etc/os-release
  [[ ${ID:-} == "ubuntu" && ${VERSION_ID:-} == "24.04" ]] || \
    die "This installer supports Ubuntu 24.04 only (detected ${PRETTY_NAME:-unknown})."
  [[ $(dpkg --print-architecture) == "amd64" ]] || \
    die "Only amd64 is currently supported."
}

prompt() {
  local variable=$1 label=$2 default=${3:-} value
  if [[ -n ${!variable:-} ]]; then
    return
  fi
  if [[ -n $default ]]; then
    read -r -p "$label [$default]: " value
    printf -v "$variable" '%s' "${value:-$default}"
  else
    while [[ -z ${value:-} ]]; do
      read -r -p "$label: " value
    done
    printf -v "$variable" '%s' "$value"
  fi
}

prompt_secret() {
  local variable=$1 label=$2 value
  if [[ -n ${!variable:-} ]]; then
    return
  fi
  while [[ -z ${value:-} ]]; do
    read -r -s -p "$label: " value
    printf '\n'
  done
  printf -v "$variable" '%s' "$value"
}

validate_network_values() {
  python3 - "$SERVER_IP" "$NEWROCK_IP" "$LAN_CIDR" "$OFFICE_DID" <<'PY'
import ipaddress
import re
import sys

server, newrock, subnet, did = sys.argv[1:]
network = ipaddress.ip_network(subnet, strict=False)
server_ip = ipaddress.ip_address(server)
newrock_ip = ipaddress.ip_address(newrock)
if server_ip not in network:
    raise SystemExit(f"Server IP {server_ip} is outside {network}")
if newrock_ip not in network:
    raise SystemExit(f"New Rock IP {newrock_ip} is outside {network}")
if server_ip == newrock_ip:
    raise SystemExit("Server and New Rock IP addresses must be different")
if not re.fullmatch(r"\+[1-9]\d{7,14}", did):
    raise SystemExit("Office DID must be E.164, for example +982112345678")
PY
  ip -o -4 addr show | awk '{print $4}' | cut -d/ -f1 | grep -Fxq "$SERVER_IP" || \
    die "SERVER_IP $SERVER_IP is not assigned to this host. Configure its static Netplan address first."
}

random_hex() { openssl rand -hex "$1"; }
random_fernet() { openssl rand -base64 32 | tr '+/' '-_' | tr -d '\n'; }

load_or_collect_configuration() {
  if [[ -r $STATE_FILE ]]; then
    # This file is root-only and contains values generated by this installer.
    # shellcheck disable=SC1090
    source "$STATE_FILE"
  fi

  local detected_ip
  detected_ip=$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") {print $(i+1); exit}}')
  detected_ip=${detected_ip:-$(hostname -I | awk '{print $1}')}

  prompt SERVER_IP "Static IPv4 address of this Ubuntu server" "$detected_ip"
  prompt NEWROCK_IP "Static IPv4 address of the New Rock HX440G"
  prompt LAN_CIDR "Office LAN subnet in CIDR notation" "192.168.1.0/24"
  prompt OFFICE_DID "Synthetic E.164 number for the first FXO line" "+982100000000"
  prompt TIMEZONE "Timezone" "Asia/Tehran"
  prompt_secret OPENAI_API_KEY "OpenAI API key"
  prompt_secret ELEVENLABS_API_KEY "ElevenLabs API key"

  POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-$(random_hex 24)}
  MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-mozaic$(random_hex 8)}
  MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-$(random_hex 24)}
  APP_SECRET_KEY=${APP_SECRET_KEY:-$(random_hex 32)}
  INTERNAL_API_KEY=${INTERNAL_API_KEY:-$(random_hex 32)}
  WEBSITE_API_KEY=${WEBSITE_API_KEY:-$(random_hex 32)}
  CREDENTIAL_ENCRYPTION_KEY=${CREDENTIAL_ENCRYPTION_KEY:-$(random_fernet)}
  LIVEKIT_API_KEY=${LIVEKIT_API_KEY:-mozaiclocal}
  LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET:-$(random_hex 32)}
  PROVISIONER_API_KEY=${PROVISIONER_API_KEY:-$(random_hex 32)}
  AMI_PASSWORD=${AMI_PASSWORD:-$(random_hex 32)}

  validate_network_values

  printf '\nConfiguration summary:\n'
  printf '  Server:       %s\n' "$SERVER_IP"
  printf '  New Rock:     %s\n' "$NEWROCK_IP"
  printf '  LAN:          %s\n' "$LAN_CIDR"
  printf '  Office DID:   %s\n' "$OFFICE_DID"
  printf '  Frontend:     http://%s:3000\n' "$SERVER_IP"
  printf '  Backend:      http://%s:8000\n' "$SERVER_IP"
  printf '  Asterisk SIP: %s:5060/udp\n' "$SERVER_IP"
  printf '  LiveKit SIP:  %s:5062/udp\n\n' "$SERVER_IP"
  read -r -p "Continue with installation? [y/N]: " answer
  [[ $answer =~ ^[Yy]$ ]] || exit 0
}

save_configuration() {
  install -d -o root -g root -m 0700 "$CONFIG_ROOT"
  umask 077
  {
    printf 'SERVER_IP=%q\n' "$SERVER_IP"
    printf 'NEWROCK_IP=%q\n' "$NEWROCK_IP"
    printf 'LAN_CIDR=%q\n' "$LAN_CIDR"
    printf 'OFFICE_DID=%q\n' "$OFFICE_DID"
    printf 'TIMEZONE=%q\n' "$TIMEZONE"
    printf 'OPENAI_API_KEY=%q\n' "$OPENAI_API_KEY"
    printf 'ELEVENLABS_API_KEY=%q\n' "$ELEVENLABS_API_KEY"
    printf 'POSTGRES_PASSWORD=%q\n' "$POSTGRES_PASSWORD"
    printf 'MINIO_ACCESS_KEY=%q\n' "$MINIO_ACCESS_KEY"
    printf 'MINIO_SECRET_KEY=%q\n' "$MINIO_SECRET_KEY"
    printf 'APP_SECRET_KEY=%q\n' "$APP_SECRET_KEY"
    printf 'INTERNAL_API_KEY=%q\n' "$INTERNAL_API_KEY"
    printf 'WEBSITE_API_KEY=%q\n' "$WEBSITE_API_KEY"
    printf 'CREDENTIAL_ENCRYPTION_KEY=%q\n' "$CREDENTIAL_ENCRYPTION_KEY"
    printf 'LIVEKIT_API_KEY=%q\n' "$LIVEKIT_API_KEY"
    printf 'LIVEKIT_API_SECRET=%q\n' "$LIVEKIT_API_SECRET"
    printf 'PROVISIONER_API_KEY=%q\n' "$PROVISIONER_API_KEY"
    printf 'AMI_PASSWORD=%q\n' "$AMI_PASSWORD"
  } > "$STATE_FILE"
  chmod 0600 "$STATE_FILE"
}

install_packages() {
  log "Installing Ubuntu packages"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y --no-install-recommends \
    asterisk asterisk-core-sounds-en-wav \
    ca-certificates curl git jq openssl python3 ufw \
    docker.io docker-compose-v2
  systemctl enable --now docker asterisk
}

sync_repo() {
  local url=$1 destination=$2
  if [[ -d $destination/.git ]]; then
    log "Updating $(basename "$destination")"
    git -C "$destination" fetch --prune origin
    git -C "$destination" pull --ff-only
  elif [[ -e $destination ]]; then
    die "$destination exists but is not a Git repository. Move it and rerun."
  else
    log "Cloning $url"
    git clone --depth 1 "$url" "$destination"
  fi
}

fetch_sources() {
  install -d -o root -g root -m 0755 "$INSTALL_ROOT"
  sync_repo "$FRONTEND_REPO" "$INSTALL_ROOT/frontend"
  sync_repo "$BACKEND_REPO" "$INSTALL_ROOT/backend"
  sync_repo "$VOICE_AGENT_REPO" "$INSTALL_ROOT/voice-agent"
  install -d -o root -g root -m 0750 "$RUNTIME_DIR"
  install -o root -g root -m 0644 "$SCRIPT_DIR/docker-compose.yml" "$RUNTIME_DIR/docker-compose.yml"
  install -o root -g root -m 0644 "$SCRIPT_DIR/provision_livekit.py" "$RUNTIME_DIR/provision_livekit.py"
  grep -Fqx 'Dockerfile.local-office' "$INSTALL_ROOT/frontend/.git/info/exclude" || \
    printf 'Dockerfile.local-office\n' >> "$INSTALL_ROOT/frontend/.git/info/exclude"
  install -o root -g root -m 0644 "$SCRIPT_DIR/Dockerfile.frontend" \
    "$INSTALL_ROOT/frontend/Dockerfile.local-office"
}

ensure_include() {
  local file=$1 line=$2
  touch "$file"
  grep -Fqx "$line" "$file" || printf '\n%s\n' "$line" >> "$file"
}

configure_asterisk() {
  log "Configuring native Asterisk"
  local ast_group ast_gid voice_ast
  ast_group=$(id -gn asterisk)
  ast_gid=$(getent group "$ast_group" | cut -d: -f3)
  [[ -n $ast_gid ]] || die "Could not resolve the Asterisk group ID."
  ASTERISK_GID=$ast_gid
  voice_ast="$INSTALL_ROOT/voice-agent/deployment/asterisk"

  install -d -o root -g "$ast_group" -m 2770 /etc/asterisk/ai-agent-generated
  install -d -o asterisk -g "$ast_group" -m 0750 /var/spool/asterisk/monitor/ai-agent
  install -d -o asterisk -g "$ast_group" -m 2770 /var/lib/asterisk/sounds/ai-agent-generated
  install -o root -g "$ast_group" -m 0640 /dev/null /etc/asterisk/ai-agent-generated/pjsip.conf
  install -o root -g "$ast_group" -m 0640 /dev/null /etc/asterisk/ai-agent-generated/extensions.conf

  cp -a /etc/asterisk/pjsip.conf "/etc/asterisk/pjsip.conf.mozaic-backup.$(date +%s)"
  cp -a /etc/asterisk/extensions.conf "/etc/asterisk/extensions.conf.mozaic-backup.$(date +%s)"
  cp -a /etc/asterisk/manager.conf "/etc/asterisk/manager.conf.mozaic-backup.$(date +%s)"

  cat > /etc/asterisk/pjsip_ai_base.conf <<EOF
; Managed by mozaic-office. Local Asterisk transport for New Rock and extensions.
[0.0.0.0-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
local_net=${LAN_CIDR}
allow_reload=yes
EOF
  ensure_include /etc/asterisk/pjsip.conf '#include pjsip_ai_base.conf'
  ensure_include /etc/asterisk/pjsip.conf '#include ai-agent-generated/pjsip.conf'
  ensure_include /etc/asterisk/extensions.conf '#include ai-agent-generated/extensions.conf'

  cat > /etc/asterisk/rtp_ai.conf <<'EOF'
[general]
rtpstart=10000
rtpend=19999
EOF
  ensure_include /etc/asterisk/rtp.conf '#include rtp_ai.conf'

  install -d -o root -g root -m 0755 /etc/asterisk/manager.d
  cat > /etc/asterisk/manager.d/ai-provisioner.conf <<EOF
[ai-provisioner]
secret=${AMI_PASSWORD}
deny=0.0.0.0/0.0.0.0
permit=127.0.0.1/255.255.255.255
read=system,call,reporting,cdr,dialplan
write=system,command,originate
writetimeout=5000
EOF
  chmod 0640 /etc/asterisk/manager.d/ai-provisioner.conf
  if grep -qE '^[[:space:]]*enabled[[:space:]]*=' /etc/asterisk/manager.conf; then
    sed -Ei '0,/^[[:space:]]*enabled[[:space:]]*=.*/s//enabled = yes/' /etc/asterisk/manager.conf
  else
    sed -i '/^\[general\]/a enabled = yes' /etc/asterisk/manager.conf
  fi
  if grep -qE '^[[:space:]]*bindaddr[[:space:]]*=' /etc/asterisk/manager.conf; then
    sed -Ei '0,/^[[:space:]]*bindaddr[[:space:]]*=.*/s//bindaddr = 127.0.0.1/' /etc/asterisk/manager.conf
  else
    sed -i '/^\[general\]/a bindaddr = 127.0.0.1' /etc/asterisk/manager.conf
  fi
  if ! grep -Eq '^#include[[:space:]]+manager\.d/\*\.conf$' /etc/asterisk/manager.conf; then
    ensure_include /etc/asterisk/manager.conf '#include manager.d/ai-provisioner.conf'
  fi

  install -o root -g root -m 0755 "$voice_ast/upload-asterisk-recording.sh" \
    /usr/local/bin/upload-asterisk-recording.sh
  install -o root -g root -m 0755 "$voice_ast/retry-pending-asterisk-recordings.sh" \
    /usr/local/bin/retry-pending-asterisk-recordings.sh
  cat > /etc/asterisk/ai-agent-recording.conf <<EOF
DASHBOARD_BACKEND_URL=http://${SERVER_IP}:8000
DASHBOARD_INTERNAL_API_KEY=${INTERNAL_API_KEY}
DELETE_AFTER_UPLOAD=false
EOF
  chown root:"$ast_group" /etc/asterisk/ai-agent-recording.conf
  chmod 0640 /etc/asterisk/ai-agent-recording.conf
  cat > /etc/cron.d/mozaic-asterisk-recordings <<'EOF'
*/5 * * * * root /usr/local/bin/retry-pending-asterisk-recordings.sh >> /var/log/asterisk/recording-upload.log 2>&1
EOF
  chmod 0644 /etc/cron.d/mozaic-asterisk-recordings
  asterisk -rx 'core restart now' || systemctl restart asterisk
}

write_runtime_configuration() {
  log "Writing Docker and application configuration"
  umask 077
  cat > "$RUNTIME_DIR/.env" <<EOF
SERVER_IP=${SERVER_IP}
BACKEND_DIR=${INSTALL_ROOT}/backend
FRONTEND_DIR=${INSTALL_ROOT}/frontend
VOICE_AGENT_DIR=${INSTALL_ROOT}/voice-agent
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
WEBSITE_API_KEY=${WEBSITE_API_KEY}
ASTERISK_GID=${ASTERISK_GID}
EOF

  cat > "$RUNTIME_DIR/backend.env" <<EOF
APP_NAME=AI Agent Dashboard
APP_ENV=production
DEBUG=false
SECRET_KEY=${APP_SECRET_KEY}
INTERNAL_API_KEY=${INTERNAL_API_KEY}
WEBSITE_API_KEY=${WEBSITE_API_KEY}
FRONTEND_URL=http://${SERVER_IP}:3000
OPENAI_API_KEY=${OPENAI_API_KEY}
ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
DATABASE_URL=postgresql+asyncpg://mozaic:${POSTGRES_PASSWORD}@postgres:5432/ai_agent_dashboard
REDIS_URL=redis://redis-dashboard:6379/0
CELERY_BROKER_URL=redis://redis-dashboard:6379/1
CELERY_RESULT_BACKEND=redis://redis-dashboard:6379/2
CREDENTIAL_ENCRYPTION_KEY=${CREDENTIAL_ENCRYPTION_KEY}
CORS_ORIGINS=["http://${SERVER_IP}:3000"]
STORAGE_ENDPOINT=http://minio:9000
STORAGE_PUBLIC_ENDPOINT=http://${SERVER_IP}:9000
STORAGE_ACCESS_KEY=${MINIO_ACCESS_KEY}
STORAGE_SECRET_KEY=${MINIO_SECRET_KEY}
STORAGE_BUCKET=ai-agent-dashboard
LIVEKIT_URL=ws://${SERVER_IP}:7880
LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
LIVEKIT_SIP_ENDPOINT=${SERVER_IP}:5062
LIVEKIT_AGENT_NAME=ai-agent-dashboard-inbound
ASTERISK_PROVISIONER_URL=http://${SERVER_IP}:9443
ASTERISK_PROVISIONER_API_KEY=${PROVISIONER_API_KEY}
ASTERISK_PUBLIC_SIP_URI=sip:${SERVER_IP}:5060;transport=udp
EOF

  cat > "$RUNTIME_DIR/voice-agent.env" <<EOF
APP_NAME=ai-agent-dashboard-voice-agent
APP_ENV=production
LOG_LEVEL=INFO
LIVEKIT_URL=ws://${SERVER_IP}:7880
LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
LIVEKIT_AGENT_NAME=ai-agent-dashboard-inbound
DASHBOARD_BACKEND_URL=http://${SERVER_IP}:8000
DASHBOARD_INTERNAL_API_KEY=${INTERNAL_API_KEY}
DEFAULT_STT_PROVIDER=openai
DEFAULT_STT_MODEL=gpt-4o-mini-transcribe
DEFAULT_LLM_PROVIDER=openai
DEFAULT_LLM_MODEL=gpt-4.1-mini
DEFAULT_TTS_PROVIDER=openai
DEFAULT_TTS_MODEL=gpt-4o-mini-tts
DEFAULT_TTS_VOICE=alloy
REALTIME_MODEL=gpt-realtime
REALTIME_INPUT_TRANSCRIPTION_MODEL=gpt-4o-mini-transcribe
REALTIME_TTS_MODEL=eleven_flash_v2_5
OPENAI_API_KEY=${OPENAI_API_KEY}
ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
ENABLE_CALL_RECORDING=false
ENABLE_USAGE_REPORTING=true
EOF

  cat > "$RUNTIME_DIR/provisioner.env" <<EOF
PROVISIONER_API_KEY=${PROVISIONER_API_KEY}
PUBLIC_SIP_URI=sip:${SERVER_IP}:5060;transport=udp
LIVEKIT_SIP_URI=sip:${SERVER_IP}:5062;transport=udp
LIVEKIT_TRANSPORT_NAME=0.0.0.0-udp
PJSIP_UDP_TRANSPORT_NAME=0.0.0.0-udp
PJSIP_TCP_TRANSPORT_NAME=0.0.0.0-tcp
PJSIP_TLS_TRANSPORT_NAME=0.0.0.0-tls
AMI_HOST=127.0.0.1
AMI_PORT=5038
AMI_USERNAME=ai-provisioner
AMI_PASSWORD=${AMI_PASSWORD}
AMI_TIMEOUT_SECONDS=10
ENABLE_RECORDING=true
RECORDING_DIRECTORY=/var/spool/asterisk/monitor/ai-agent
RECORDING_UPLOADER=/usr/local/bin/upload-asterisk-recording.sh
OUTBOUND_MEDIA_DIRECTORY=/var/lib/asterisk/sounds/ai-agent-generated
BACKEND_OUTBOUND_CALLBACK_URL=http://${SERVER_IP}:8000/api/v1/internal/outbound/events
BACKEND_INTERNAL_API_KEY=${INTERNAL_API_KEY}
STATE_FILE=/var/lib/asterisk-provisioner/connections.json
GENERATED_PJSIP_FILE=/etc/asterisk/ai-agent-generated/pjsip.conf
GENERATED_DIALPLAN_FILE=/etc/asterisk/ai-agent-generated/extensions.conf
EOF

  cat > "$RUNTIME_DIR/livekit.yaml" <<EOF
port: 7880
log_level: info
rtc:
  tcp_port: 7881
  udp_port: 7882
  use_external_ip: false
  node_ip: ${SERVER_IP}
redis:
  address: 127.0.0.1:6380
keys:
  ${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}
EOF

  cat > "$RUNTIME_DIR/sip.yaml" <<EOF
api_key: ${LIVEKIT_API_KEY}
api_secret: ${LIVEKIT_API_SECRET}
ws_url: ws://127.0.0.1:7880
redis:
  address: 127.0.0.1:6380
sip_port: 5062
sip_port_listen: 5062
sip_hostname: ${SERVER_IP}
rtp_port: 20000-29999
listen_ip: 0.0.0.0
local_net: ${LAN_CIDR}
nat_1_to_1_ip: ${SERVER_IP}
use_external_ip: false
symmetric_rtp: true
logging:
  level: info
EOF

  cat > "$RUNTIME_DIR/redis-livekit.conf" <<'EOF'
bind 127.0.0.1
protected-mode yes
port 6380
appendonly yes
dir /data
EOF
  chmod 0600 "$RUNTIME_DIR"/.env "$RUNTIME_DIR"/*.env "$RUNTIME_DIR"/*.yaml
  chmod 0644 "$RUNTIME_DIR/redis-livekit.conf" "$RUNTIME_DIR/docker-compose.yml" \
    "$RUNTIME_DIR/provision_livekit.py"
}

configure_firewall() {
  if ! ufw status | grep -q '^Status: active'; then
    log "UFW is inactive; rules were not enabled to avoid locking out remote access."
    return
  fi
  log "Adding LAN-restricted UFW rules"
  ufw allow OpenSSH
  ufw allow from "$LAN_CIDR" to "$SERVER_IP" port 3000 proto tcp comment 'Mozaic frontend'
  ufw allow from "$LAN_CIDR" to "$SERVER_IP" port 8000 proto tcp comment 'Mozaic backend'
  ufw allow from "$LAN_CIDR" to "$SERVER_IP" port 7880 proto tcp comment 'LiveKit API'
  ufw allow from "$LAN_CIDR" to "$SERVER_IP" port 7881 proto tcp comment 'LiveKit RTC TCP'
  ufw allow from "$LAN_CIDR" to "$SERVER_IP" port 7882 proto udp comment 'LiveKit RTC UDP'
  ufw allow from "$LAN_CIDR" to "$SERVER_IP" port 9000 proto tcp comment 'Mozaic recordings'
  ufw allow from "$NEWROCK_IP" to "$SERVER_IP" port 5060 proto udp comment 'New Rock SIP'
  ufw allow from "$NEWROCK_IP" to "$SERVER_IP" port 10000:19999 proto udp comment 'New Rock RTP'
}

compose() {
  docker compose --env-file "$RUNTIME_DIR/.env" -f "$RUNTIME_DIR/docker-compose.yml" "$@"
}

wait_http() {
  local name=$1 url=$2 header=${3:-} attempt
  for attempt in $(seq 1 60); do
    if [[ -n $header ]]; then
      curl --silent --fail -H "$header" "$url" >/dev/null && return 0
    else
      curl --silent --fail "$url" >/dev/null && return 0
    fi
    sleep 2
  done
  die "$name did not become healthy: $url"
}

wait_tcp() {
  local name=$1 host=$2 port=$3 attempt
  for attempt in $(seq 1 60); do
    if timeout 2 bash -c "</dev/tcp/${host}/${port}" 2>/dev/null; then
      return 0
    fi
    sleep 2
  done
  die "$name did not open ${host}:${port}"
}

start_stack() {
  log "Building and starting the local stack"
  cd "$RUNTIME_DIR"
  compose pull postgres redis-dashboard redis-livekit minio livekit livekit-sip
  compose up -d postgres redis-dashboard redis-livekit minio minio-init livekit livekit-sip
  wait_tcp "LiveKit" "$SERVER_IP" 7880
  compose up -d --build api
  wait_http "Dashboard backend" "http://${SERVER_IP}:8000/health"
  compose run --rm api alembic upgrade head
  compose up -d --build celery-worker celery-beat frontend asterisk-provisioner voice-agent
  wait_http "Asterisk provisioner" "http://${SERVER_IP}:9443/health" \
    "X-Provisioner-API-Key: ${PROVISIONER_API_KEY}"

  log "Creating the central LiveKit SIP trunk and dispatch rule"
  compose exec -T \
    -e SERVER_IP="$SERVER_IP" \
    -e LIVEKIT_URL="ws://${SERVER_IP}:7880" \
    -e LIVEKIT_API_KEY="$LIVEKIT_API_KEY" \
    -e LIVEKIT_API_SECRET="$LIVEKIT_API_SECRET" \
    api python /opt/mozaic/provision_livekit.py
  systemctl restart asterisk
}

install_control_command() {
  install -o root -g root -m 0755 "$SCRIPT_DIR/office-control.sh" /usr/local/sbin/mozaic-office
}

write_newrock_guide() {
  cat > "$INSTALL_ROOT/NEWROCK-HX440G.txt" <<EOF
New Rock HX440G - first FXO line
================================
New Rock IP:              ${NEWROCK_IP}
SIP proxy/server:         ${SERVER_IP}
SIP port:                 5060 UDP
Registration:             disabled (IP trunk/peer mode)
NAT traversal:            disabled
Preferred codecs:         PCMA (G.711 A-law), then PCMU
DTMF:                     RFC2833/RFC4733
FXO inbound/hotline DID:  ${OFFICE_DID}
Inbound SIP target:       sip:${OFFICE_DID}@${SERVER_IP}:5060

Create this phone number in Dashboard:
{
  "name": "Office New Rock",
  "provider": "generic_sip",
  "phone_number": "${OFFICE_DID}",
  "agent_id": "YOUR_AGENT_UUID",
  "sip": {
    "mode": "ip_trunk",
    "server_uri": "sip:${NEWROCK_IP}:5060",
    "allowed_addresses": ["${NEWROCK_IP}/32"],
    "transport": "udp"
  }
}

After creating it, press Provision in Dashboard. For outbound calls, configure
the HX440G digit map to translate +98... to the local 0... dialling format.
EOF
  chmod 0644 "$INSTALL_ROOT/NEWROCK-HX440G.txt"
}

final_checks() {
  log "Running final checks"
  compose ps
  asterisk -rx 'pjsip show transports'
  asterisk -rx 'pjsip show endpoint ai-livekit' || true
  curl --silent --fail "http://${SERVER_IP}:8000/health" | jq .
  curl --silent --fail -H "X-Provisioner-API-Key: ${PROVISIONER_API_KEY}" \
    "http://${SERVER_IP}:9443/health" | jq .
  log "Installation completed"
  printf '\nDashboard: http://%s:3000\n' "$SERVER_IP"
  printf 'Backend:   http://%s:8000/docs\n' "$SERVER_IP"
  printf 'New Rock:  %s\n' "$INSTALL_ROOT/NEWROCK-HX440G.txt"
  printf 'Operations: sudo mozaic-office status|health|logs|restart|update\n'
}

main() {
  require_root
  check_os
  touch "$LOG_FILE"
  chmod 0600 "$LOG_FILE"
  load_or_collect_configuration
  save_configuration
  timedatectl set-timezone "$TIMEZONE"
  install_packages
  fetch_sources
  configure_asterisk
  write_runtime_configuration
  configure_firewall
  install_control_command
  write_newrock_guide
  start_stack
  final_checks
}

if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
  main "$@"
fi
